build:
  maxIssues: 20
  excludeCorrectable: false

style:
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000', '60']
  UnusedPrivateMember:
    active: true

complexity:
  TooManyFunctions:
    active: true
  LongMethod:
    active: true
